### ISSUE TITLE
Default content somehow breaks on import

### ISSUE THREAD

**Issue by dawehner** [larowlan/default_content#16]
In case you start with an install profile and a `drush cim` of the full config folder somehow caches are not cleared properly so that default_content_modules_installed() triggers an undefined entity type exception.

Not sure what this is causing, just wanted to track the issue.

**Comment by Berdir** [comment]
including enabling modules? That is special, config entities are then not imported from the module but only later from the staged configuration. hook_modules_enabled() runs before that. I guess all we can do is disable it when we're in config sync mode? see forum_install() as an example.

**Comment by dawehner** [comment]
Good idea! Together with drush commands to import content from a specific dir, we basically have all we need?

**Comment by larowlan** [comment]
Is this something we can reproduce in a test?
fix in forum looks simple enough

**Comment by dawehner** [comment]
Well, I just see the behaviour in a full import, I guess we want to have a more specific test.

**Comment by benjy** [comment]
I had this exact problem today. Not sure if it's relevant but i was developing an install profile with a module under profiles/profilename/modules. I used the drush command in PR #22 to get around the issue for now.

**Comment by rcaracaus** [comment]
I am getting this too on a fresh install with a basic article node. I think what is happening is that the default_content module is trying to do the import before the configuration has built the article content type. It could be because I am not using the drupal patch that helps sync config and I am just using the config/install, but that is a wild guess. #22 worked for me me but I needed to change 

```
$default_content_manager = \Drupal::service('default_content.manager');
```

to

```
$default_content_manager = \Drupal::service('default_content.importer');
```

**Comment by rcaracaus** [comment]
Since I was going to use drush to import above anyway, I just drush enabled the module after the drush site-install so I didn't need to use a forked version of the module and that worked.

**Comment by larowlan** [comment]
Hey @rcaracaus how's things!

Please use the module off drupal.org, this one here is way out of date

**Comment by rcaracaus** [comment]
@larowlan things are good, cruising in Costa Rica still! I did use the Drupal.org version, I just got here via google.
