### ISSUE TITLE
Discuss implications of a module rename

### ISSUE THREAD

**Issue by larowlan** [larowlan/default_content#48]
The project here is default_content
The project on d.o (where we want to end up) is defaultcontent

How disruptive will it be to those using it if we rename it before pushing to d.o

Straw poll.

Votes close 25th August.

**Comment by larowlan** [comment]
:+1: for moving to d.o and consistent naming google_analytics/googleanalytics has always tripped me up

**Comment by larowlan** [comment]
Other option is push to d.o as default_content but that is very confusing given we already have defaultcontent, I'd be :-1: on that

**Comment by nickschuch** [comment]
+1

**Comment by kimpepper** [comment]
I vote for default_content for consistency (and because defaultcontent is taken??)

Otherwise, a more dramatic change to "installable_content" or similar.

**Comment by Sam152** [comment]
I'd leave it as default_content and link between the two projects on d.org.
- default_content seems like it would be nicer to read in code than defaultcontent.
- Wouldn't have to change the existing project.
- The D7 project doesn't have that many installs, there isn't a massive mind share around it.

**Comment by davereid** [comment]
:+1: for default_content

**Comment by dawehner** [comment]
Yeah default_content is easier to read for some reason.

**Comment by Berdir** [comment]
No strong opinion. Already going through module addition/renames in our project with plugin_discovery/plugin. I know what I have to do now.

**Comment by andypost** [comment]
+1 to default_content easy to read

**Comment by larowlan** [comment]
Ok we're on d.o now as default_content

**Comment by larowlan** [comment]
https://www.drupal.org/project/default_content
