### ISSUE TITLE
Delete/Uninstall Default Content Nodes?

### ISSUE THREAD

**Issue by justinlevi** [larowlan/default_content#58]
Uninstalling the module does not seem to delete the default_content nodes. We have a use case where it would be very helpful to be able to delete the default content by either uninstalling the custom module or running a drush command.

**Comment by larowlan** [comment]
Correct, that's how it's built. 

You know the uuids so you can delete them later if needed

**Comment by justinlevi** [comment]
@larowlan Thanks for the response. How would you go about deleting them later? 

Would it be useful to include a deleteContent method that runs on the hook_module_uninstall?

**Comment by justinlevi** [comment]
Here's a WIP PR showing what I was thinking. 
https://github.com/larowlan/default_content/pull/59
